language: python
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"

before_script:
  - pip install -r requirements-test.txt

script:
  - python setup.py flake8
  - pytest || true
